#!/bin/sh

startingURL="${1}"
shift
searchString=$@

wget --mirror --quiet --no-parent "${startingURL}"

find * -type f -name "msg*.html" -exec grep -q "${searchString}" {} \; -exec sh email-to-cvs {} \;
